import type { Partner } from "./types";

export const partners: readonly Partner[] = [
  {
    slug: "itm",
    name: "Instituto Tecnológico Metropolitano",
    shortName: "ITM",
    role: "proponente",
    axis: "academia",
    order: 0,
    logo: "/logos-institucionales/logo-itm.png",
  },
  {
    slug: "ufpso",
    name: "Universidad Francisco de Paula Santander Ocaña",
    shortName: "UFPSO",
    role: "aliado",
    axis: "academia",
    order: 1,
    logo: "/logos-institucionales/logo-ufps.jpg",
  },
  {
    slug: "udla",
    name: "Universidad de la Amazonia",
    shortName: "Uniamazonia",
    role: "aliado",
    axis: "academia",
    order: 2,
    logo: "/logos-institucionales/logo-uni-amazonia.png",
  },
  {
    slug: "utch-cierc",
    name: "Centro de Investigación en Energías Renovables y Climatología – Universidad Tecnológica del Chocó",
    shortName: "UTCH – CIERC",
    role: "aliado",
    axis: "academia",
    order: 3,
    logo: "/logos-institucionales/logo-uni-choco.png",
  },
  {
    slug: "iue",
    name: "Institución Universitaria de Envigado",
    shortName: "IUE",
    role: "aliado",
    axis: "academia",
    order: 4,
    logo: "/logos-institucionales/logo-iue.png",
  },
  {
    slug: "ufro",
    name: "Universidad de la Frontera",
    shortName: "UFRO",
    role: "aliado",
    axis: "academia",
    order: 5,
    country: "Chile",
    logo: "/logos-institucionales/logo-ufro.png",
  },
  {
    slug: "natucafe",
    name: "Natucafé S.A.S",
    role: "aliado",
    axis: "empresa",
    order: 6,
  },
  {
    slug: "terra-cann",
    name: "Terra Cann Colombia S.A.S",
    role: "aliado",
    axis: "empresa",
    order: 7,
  },
  {
    slug: "gentech",
    name: "Gentech Biosciences S.A.S",
    role: "aliado",
    axis: "empresa",
    order: 8,
  },
  {
    slug: "ingelight-mey",
    name: "Ingelight-Mey S.A.S",
    role: "aliado",
    axis: "empresa",
    order: 9,
  },
  {
    slug: "cordeing",
    name: "Cordeing S.A.S",
    role: "aliado",
    axis: "empresa",
    order: 10,
  },
  {
    slug: "siaa",
    name: "Sociedad Ingenieros Agrónomos de Antioquia",
    role: "beneficiario",
    axis: "sociedad",
    order: 11,
  },
  {
    slug: "iall",
    name: "Asociación de Ingenieros Agrónomos del Llano",
    role: "beneficiario",
    axis: "sociedad",
    order: 12,
  },
  {
    slug: "iaag",
    name: "Asociación de Ingenieros Agrónomos de La Guajira",
    role: "beneficiario",
    axis: "sociedad",
    order: 13,
  },
] as const;
